version: 1.0.{build}
image: Visual Studio 2017

environment:
  OPENCOVER_VER: 4.6.519
  CODECOVTOKEN:
    secure: lcLrgEyHk1S8n86gQjdwSS2PSPRQ7S8+PXrr+ic67ktJp4i9Hz+FtMUaIjj8rMbC
  SONARTOKEN:
    secure: Ff4Kpig3CbIgOJ37jcA42xpHhbBN7Gn6qjGhxeD8BEFz5sVSPoFZKvqz6SokTywQ


before_build:
- cmd: >-
    nuget restore

    nuget install -OutputDirectory packages -Version %OPENCOVER_VER% OpenCover

build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - SonarQube.Scanner.MSBuild.exe begin /k:"garoyeri-superfizzbuzz" /d:sonar.organization="garoyeri-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="%SONARTOKEN%" /d:sonar.cs.opencover.reportsPaths="%CD%\coverage.xml"
  - msbuild "SuperFizzBuzz.sln" /verbosity:minimal

test_script:
  - cmd: packages\OpenCover.%OPENCOVER_VER%\tools\OpenCover.Console.exe -register:user -target:"%PROGRAMFILES%\dotnet\dotnet.exe" -targetargs:"test SuperFizzBuzz.Core.Tests" -output:"coverage.xml" -filter:"+[SuperFizzBuzz.Core*]* -[SuperFizzBuzz.Core.Tests*]*" -oldstyle

after_build:
  - dotnet pack SuperFizzBuzz.Core /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

after_test:
  - SonarQube.Scanner.MSBuild.exe end /d:sonar.login="%SONARTOKEN%"

artifacts:
  - path: 'SuperFizzBuzz.Core\bin\Debug\*.nupkg'
