version: 1.0.{build}
image: Visual Studio 2017

environment:
  OPENCOVER_VER: 4.6.519
  CODECOVTOKEN:
    secure: lcLrgEyHk1S8n86gQjdwSS2PSPRQ7S8+PXrr+ic67ktJp4i9Hz+FtMUaIjj8rMbC


before_build:
- cmd: >-
    nuget restore

    nuget install -Verbosity quiet -OutputDirectory packages -Version %OPENCOVER_VER% OpenCover

build:
  project: SuperFizzBuzz.sln
  verbosity: minimal

test_script:
  - cmd: packages\OpenCover.%OPENCOVER_VER%\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"SuperFizzBuzz.Core.Tests.dll -noshadow" -output:"coverage.xml" -filter:"+[SuperFizzBuzz.Core*]* -[SuperFizzBuzz.Tests*]*"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t $env:CODECOVTOKEN
